version: '3.8'

services:
  manufacturer-backend:
    build: .
    container_name: blocker_manufacturer_backend
    ports:
      - "5002:5002"
    volumes:
      - ./crypto/keys:/app/crypto/keys
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped